services:
  andreo.oauth_client.middleware_aggregate.facebook:
    class: Andreo\OAuthApiConnectorBundle\Middleware\MiddlewareAggregate
    arguments:
      - '@Andreo\OAuthApiConnectorBundle\Middleware\MiddlewareAggregate'
